mmorpg_bbs/bbs/urls.py
from django.urls import path

from .views import (
    AdDelete,
    AdDetail,
    AdEdit,
    AdSearch,
    AdsList,
    create_ad,
    # AdImagesCreate,
    response_accept,
    response_delete,
)

app_name = 'bbs'

urlpatterns = [
    path('', AdsList.as_view(), name='main'),
    path('<int:pk>', AdDetail.as_view(), name='detail'),
    path('search', AdSearch.as_view(), name='search'),
    path('add', create_ad, name='add'),
    path('<int:pk>/edit', create_ad, name='edit'),
    path('<int:pk>/delete', AdDelete.as_view(), name='delete'),
    path('response_accept/<int:pk>', response_accept, name='response_accept'),
    path('response_delete/<int:pk>', response_delete, name='response_delete'),
]

mmorpg_bbs/mmorpg_bbs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from user_profiles import views as user_profiles_views

urlpatterns = [
    path('', include('bbs.urls', namespace='bbs')),
    path('profile/', include('user_profiles.urls', namespace='user_profiles')),
    path('sign_up/', user_profiles_views.sign_up, name='sign_up'),
    path('sign_in/', user_profiles_views.sign_in, name='sign_in'),
    path('sign_out/', user_profiles_views.sign_out, name='sign_out'),
    path('otp_check/', user_profiles_views.otp_check, name='otp_check'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

mmorpg_bbs/templates/layout/default.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

<title>
{% block title %}
{% endblock title %}
</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark-subtle" data-bs-theme="dark">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link {% block nav_main_class %}{% endblock %}" href="{% url 'bbs:main' %}">Main</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block nav_search_class %}{% endblock %}" href="{% url 'bbs:search' %}">Search <i class="bi bi-search"></i></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% block nav_add_class %}{% endblock %}" href="{% url 'bbs:add' %}">New ad <i class="bi bi-plus-square"></i></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            {% block login_logout_buttons %}
            {% endblock %}
        </div>
    </nav>
    
    <div role="main" class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
    </div>
{% load cache %}
{% cache 300 footer %}
    {% include './parts/footer.html' %}
{% endcache %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>