mmorpg_bbs/bbs/urls.py
from django.urls import path

from .views import (
    AdDelete,
    AdDetail,
    AdEdit,
    AdSearch,
    AdsList,
    create_ad,
    # AdImagesCreate,
    response_accept,
    response_delete,
)

app_name = 'bbs'

urlpatterns = [
    path('', AdsList.as_view(), name='main'),
    path('<int:pk>', AdDetail.as_view(), name='detail'),
    path('search', AdSearch.as_view(), name='search'),
    path('add', create_ad, name='add'),
    path('<int:pk>/edit', create_ad, name='edit'),
    path('<int:pk>/delete', AdDelete.as_view(), name='delete'),
    path('response_accept/<int:pk>', response_accept, name='response_accept'),
    path('response_delete/<int:pk>', response_delete, name='response_delete'),
]

mmorpg_bbs/mmorpg_bbs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from user_profiles import views as user_profiles_views

urlpatterns = [
    path('', include('bbs.urls', namespace='bbs')),
    path('profile/', include('user_profiles.urls', namespace='user_profiles')),
    path('sign_up/', user_profiles_views.sign_up, name='sign_up'),
    path('sign_in/', user_profiles_views.sign_in, name='sign_in'),
    path('sign_out/', user_profiles_views.sign_out, name='sign_out'),
    path('otp_check/', user_profiles_views.otp_check, name='otp_check'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

mmorpg_bbs/user_profiles/urls.py
from django.urls import path

from .views import profile

app_name = 'user_profiles'

urlpatterns = [
    path('', profile, name='profile'),
]

mmorpg_bbs/bbs/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


class Ad(models.Model):

    class Category(models.TextChoices):
        TANK = 'TK', 'Tanks'
        HEAL = 'HL', 'Heals'
        DD = 'DD', 'Damagedealers'
        MERCHANT = 'MR', 'Merchants'
        GUILDMASTER = 'GM', 'Guildmasters'
        QUESTGIVER = 'QG', 'Questgivers' 
        BLACKSMITH = 'BS', 'Blacksmiths'
        LEATHERMAN = 'LM', 'Leathermans'
        POTIONMASTER = 'PM', 'Potionmasters'
        SPELLMASTER = 'SM', 'Spellmasters'

    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=2, choices=Category.choices, default=Category.TANK)

    def __str__(self):
        return f'#{self.pk}, title: {self.title}, category: {self.get_category_display()}, user: {self.user.username},'

    def get_absolute_url(self):
        return f'/{self.id}'

class Response(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f'#{self.pk}, ad: {self.ad.pk}, user: {self.user.username}, text: {self.text[:5]}..., accepted: {self.accepted}'


class Picture(models.Model):
    image = models.ImageField(upload_to='ads_pictures')
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        output_size = (800, 500)
        img = img.resize(output_size)
        img.save(self.image.path)

mmorpg_bbs/bbs/forms.py
from django import forms
from django.forms import ModelForm, ClearableFileInput
from .models import Ad, Response

class ResponseForm(ModelForm):
    class Meta:
        model = Response
        fields = ('text', 'ad', 'user')
        labels = {
            'text': 'Response Text',
        }
        widgets = {
            'text': forms.TextInput(),
            'ad': forms.HiddenInput(),
            'user': forms.HiddenInput(),
        }



class MultipleFileInput(ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class AdForm(ModelForm):
    class Meta:
        model = Ad
        fields = ('category', 'title', 'text', 'price', 'user')
        widgets = {
            'user': forms.HiddenInput(),
        }



class AdImageForm(forms.Form):
    image = MultipleFileField(required=False)

mmorpg_bbs/bbs/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.views.generic.edit import FormMixin

from .filters import AdFilter
from .forms import AdForm, AdImageForm, ResponseForm
from .models import Ad, Picture, Response


@login_required
def response_accept(request, pk):
    resp = Response.objects.get(pk=pk)
    acpt = resp.accepted
    resp.accepted = not acpt
    resp.save()
    messages.success(request, f"Response from {resp.user.username} {'rejected' if acpt else 'accepted'}!")
    return redirect(resp.ad.get_absolute_url())


@login_required
def response_delete(request, pk):
    resp = Response.objects.get(pk=pk)
    url = resp.ad.get_absolute_url()
    username = resp.user.username
    resp.delete()
    messages.success(request, f"Response from {username} 'deleted'!")
    return redirect(url)


class AdsList(ListView):
    model = Ad
    template_name = 'bbs/main.html'
    context_object_name = 'ads'
    ordering = '-created'
    paginate_by = 10


class AdDetail(FormMixin, DetailView):
    model = Ad
    template_name = 'bbs/ad.html'
    context_object_name = 'ad'
    form_class = ResponseForm

    def get_success_url(self):
        return reverse_lazy('bbs:detail', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super(AdDetail, self).get_context_data(**kwargs)
        context['form'] = ResponseForm(initial={'ad': self.object, 'user': self.request.user})
        context['responses'] = Response.objects.filter(ad=self.object).order_by('-created')
        context['pictures'] = Picture.objects.filter(ad=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(AdDetail, self).form_valid(form)



class AdSearch(AdsList):
    template_name = 'bbs/search.html'
    paginate_by = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = AdFilter(self.request.GET, queryset=self.get_queryset())
        return context


@login_required
def create_ad(request, pk=None):
    if pk:
        instance = Ad.objects.get(pk=pk)
        caption = 'Edit Ad'
    else:
        instance = None
        caption = 'Create Ad'
    if request.method == "POST":
        form_ad = AdForm(request.POST, initial={'user': request.user})
        form_images = AdImageForm(request.POST, request.FILES)
        images = request.FILES.getlist('image')
        if form_ad.is_valid() and form_images.is_valid():
            if instance:
                instance.title=form_ad.cleaned_data['title']
                instance.text=form_ad.cleaned_data['text']
                instance.price=form_ad.cleaned_data['price']
                instance.category=form_ad.cleaned_data['category']
            else:
                instance = Ad.objects.create(
                    user=request.user,
                    title=form_ad.cleaned_data['title'],
                    text=form_ad.cleaned_data['text'],
                    price=form_ad.cleaned_data['price'],
                    category=form_ad.cleaned_data['category'],
                )
            instance.save()
            for img in images:
                pic = Picture.objects.create(ad=instance, image=img)
                pic.save()
            return redirect('bbs:main')
    else:
        
        form_ad = AdForm(initial={'user': request.user}, instance=instance)
        form_images = AdImageForm()
    context = {'form_ad': form_ad, 'form_images': form_images, 'caption': caption}
    return render(request, 'bbs/create.html', context)


class AdEdit(PermissionRequiredMixin, UpdateView):
    template_name = 'bbs/create.html'
    model = Ad
    fields = ('category', 'title', 'text','price')
    exclude = ('user',)
    permission_required = ('bbs.change_ad', )

    def get_success_url(self):
        return reverse_lazy('bbs:detail', kwargs={'pk': self.kwargs['pk']})

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Ad.objects.get(pk=id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['caption'] = 'Edit Ad'
        return context


class AdDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'bbs/delete.html'
    queryset = Ad.objects.all()
    success_url = reverse_lazy('bbs:main')
    permission_required = ('bbs.delete_ad', )

mmorpg_bbs/bbs/templates/bbs/ad.html
{% extends 'bbs/base.html' %}

{% block title %}
Ad: {{ ad.title|truncatewords:3 }}
{% endblock title %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="card m-2">
        <div class="card-header container">

          {% if pictures %}
          <div class="row justify-content-center">
            <div class="col-md-4">
          <div id="carouselExampleCaptions" class="carousel slide carousel-dark" style="max-height: 500px; max-width: 800px;overflow: hidden;">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              {% for pic in pictures %}

              {% if not forloop.first %}
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{forloop.counter0}}" aria-label="Slide {{forloop.counter}}"></button>
              {% endif %}
              {% endfor %}
              
              
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{{ pictures.0.image.url }}" class="d-block w-100" alt="{{ pictures.0.image.caption }}">
              </div>

              {% for pic in pictures %}

              {% if not forloop.first %}
                <div class="carousel-item">
                  <img src="{{pic.image.url}}" class="d-block w-100" alt=".image.url">
                </div>
              {% endif %}
              {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
      </div>

          {% endif %}

          <h3>{{ ad.title }}</h3>
          <p>Created: {{ ad.created|date:'d-m-Y H:s' }}</p>
          <div>
            Category: <span class="badge bg-info">{{ ad.get_category_display }}</span>
            <br>
            User: <span class="badge bg-info">{{ ad.user.username }}</span>
            <br>
          </div>
        </div>
        <div class="card-body">{{ ad.text }}</div>
        <div class="card-footer">
                {% if user == ad.user %}
                  <a class="btn btn-sm btn-outline-danger float-end m-2" href="{% url 'bbs:delete' ad.id %}" role="button">
                    <i class="bi bi-trash"></i>
                    Delete
                  </a>
                  <a class="btn btn-sm btn-outline-warning float-end m-2" href="{% url 'bbs:edit' ad.id %}" role="button">
                    <i class="bi bi-pencil"></i>
                    Edit
                  </a>
                {% elif user.is_authenticated %}
                <form method="POST">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <input class="btn btn-sm btn-outline-primary float-end" type="submit" value="Respond"/>
                </form>
                {% endif %}

                <h4 class="m-2">Price: <span class="badge rounded-pill text-bg-warning">{{ ad.price }}</span></h4>
        </div>
      </div>
      {% if responses %}
        <h4 class="m-2">Responses:</h4>
      {% endif %}
      
      {% for resp in responses %}
        
          <div class="card m-2">
            <div class="card-body container">
                <div class="row">
                  <div class="col-9">
                    <h5 class="card-title">
                      <img class="img-fluid img-thumbnail rounded-circle" src="{{ resp.user.profile.avatar.url }}" width="25" />
                      {{resp.user}}
                    </h5>
                    <p class="card-text">{{resp.text|truncatewords:10}}</p>
                  </div>
                  {% if ad.user == user %}

                  
                  <div class="col-3">
                      <a class="btn btn-sm btn-outline-danger float-end m-2" href="{% url 'bbs:response_delete' resp.id %}" role="button">
                        <i class="bi bi-trash"></i>
                        Delete
                      </a>
                      <a class="btn btn-sm btn-outline-info float-end m-2" href="{% url 'bbs:response_accept' resp.id %}" role="button">
                        {% if resp.accepted %}
                          Reject
                        {% else %}
                          Accept
                        {% endif %}  
                        
                      </a>
                      <h2 class="m-1">
                      {% if resp.accepted %}
                        <i class="bi bi-check-square float-end"></i>
                      {% else %}
                        <i class="bi bi-square float-end"></i>
                      {% endif %}
                      </h2>
                  </div>
                 {% endif %}  
                 
              </div>
            </div>
          </div>
      {% empty %}
      <h4 class="m-2">No responses yet...</h4>
      {% endfor %}

{% endblock content %}

mmorpg_bbs/bbs/templates/bbs/base.html
{% extends "layout/default.html" %}

{% block login_logout_buttons %}
    {% if user.is_authenticated %}
        <div class="dropdown">
            <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img class="img-fluid img-thumbnail rounded-circle" src="{{ user.profile.avatar.url }}" width="25" />
                &nbsp;
                {{user.username}}
            </button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'user_profiles:profile' %}">
                    <i class="bi bi-person"></i>
                    Profile
                </a>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    <i class="bi bi-door-closed"></i>
                    Sign Out
                </a>
              </li>
            </ul>
          </div>

          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Signing out</h1>
                </div>
                <div class="modal-body">
                  Are you sure you want to sign out?
                </div>
                <div class="modal-footer">
                  <a class="btn btn-outline-success" data-bs-dismiss="modal">
                    <i class="bi bi-x-circle"></i>
                    Cancel
                  </a>
                  <a class="btn btn-outline-danger" href="{% url 'sign_out' %}">
                    <i class="bi bi-door-closed"></i>
                    Sign out
                  </a>
                </div>
              </div>
            </div>
          </div>
          
          

    {% else %}
        <a class="btn btn-outline-primary" href="{% url 'sign_in' %}">Sign In</a>
    {% endif %}
{% endblock %}

mmorpg_bbs/bbs/templates/bbs/create.html
{% extends 'bbs/base.html' %} 

{% block title %} 
{{ caption }}
{% endblock title %} 

{% block nav_add_class %}active{% endblock %}

{% block content %}

<h3>{{ caption }}</h3>

{% load crispy_forms_tags %}



<form class="form" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form_ad|crispy}}
  <br><br>
  {{form_images|crispy}}
  <input class="btn btn-success my-3" type="submit" value="{{ caption }}"/>
</form>



{% endblock content %}

mmorpg_bbs/bbs/templates/bbs/delete.html
{% extends 'bbs/base.html' %} 

{% block title %} 
  Delete ad
{% endblock title %} 

{% block content %}

<h3>Delete ad?</h3>
<div class="card">
    <div class="card-header">
      <h3>{{ ad.title }}</h3>
      <h4>Posted: {{ ad.created|date:'d-m-Y H:s' }}</h4>
      <div>
        Category: <span class="badge bg-info">{{ ad.get_category_display }}</span>
        <br>
        User: <span class="badge bg-info">{{ ad.user.username }}</span>
        <br>
      </div>
    </div>
    <div class="card-body">{{ ad.text }}</div>
  </div>
<form method="POST">
  {% csrf_token %}
  <input class="btn btn-danger my-3" type="submit" value="Delete" />
</form>

{% endblock content %}

mmorpg_bbs/bbs/templates/bbs/mail_new_ads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{ username }}!</h1>
    <h2>New ads on portal for {{mailing_period}} day(s)</h2>
    {% for ad in ads %}
    <h4>{{ ad.title }}</h4>
    <h5>Category: {{ ad.get_category_display }}</h5>
    <h5>Price: {{ ad.price }}</h5>
    Открыть: <a href="http://127.0.0.1:8000{% url 'bbs:detail' pk=ad.pk %}">http://127.0.0.1:8000{% url 'bbs:detail' pk=ad.pk %}</a>
    <hr>
    {% endfor %}
</body>
</html>

mmorpg_bbs/bbs/templates/bbs/mail_new_response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{ username }}!</h1>
    <h2>New response to your ad {{ad_title}} from {{responder_username}}!</h2>
    <br>
    <p> {{ response_text }} </p>
    Open: <a href="http://127.0.0.1:8000{% url 'bbs:detail' pk=ad_pk %}">http://127.0.0.1:8000{% url 'bbs:detail' pk=ad_pk %}</a>
</body>
</html>

mmorpg_bbs/bbs/templates/bbs/main.html
{% extends 'bbs/base.html' %}

{% block nav_main_class %}active{% endblock %}

{% block title %}
MMORPG Ad Portal
{% endblock title %}

{% block content %}
    <h1>MMORPG Ad Portal</h1>
    <!-- <h2>Общее число постов: {{ posts|length }}</h2> -->
    <h2>Total ad count: {{ page_obj.paginator.count }}</h2>
    {% if is_paginated %} <h4>Page: {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</h4> {% endif %}
    <hr>
    {% if ads %}
        <table class="table">
            <tr>
                <th scope="col">
                    User
                </th>
                <th scope="col">
                    Category
                </th>
                <th scope="col">
                    Title
                </th>
                <th scope="col">
                    Posted
                </th>
                <th scope="col">
                    Price
                </th>
                <th scope="col">
                    Actions
                </th>         
            </tr>
            {% for ad in ads %}
            <tr>
                <td>{{ ad.user.username }}</td>
                <td>
                    {{ ad.get_category_display }}
                </td>
                <td>
                    <a href="{% url 'bbs:detail' ad.id %}">{{ ad.title }}</a>
                </td>
                <td>
                    <a href="{% url 'bbs:detail' ad.id %}">{{ ad.created|date:'d M Y H:s' }}</a>
                </td>
                <td>{{ ad.price }}</td>
                <td>
                    <a class="btn btn-sm btn-outline-primary m-1" href="{% url 'bbs:detail' ad.id %}" role="button">
                        <i class="bi bi-binoculars"></i>
                        View
                    </a>
                    {% if user == ad.user %}
                        <a class="btn btn-sm btn-outline-warning m-1" href="{% url 'bbs:edit' ad.id %}" role="button">
                            <i class="bi bi-pencil"></i>
                            Edit
                        </a>
                        <a class="btn btn-sm btn-outline-danger m-1" href="{% url 'bbs:delete' ad.id %}" role="button">
                            <i class="bi bi-trash"></i>
                            Delete
                        </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <br>
        {% include 'bbs/parts/paginator.html' %}
    {% else %}
        <h2>Nothing to show =(</h2>
    {% endif %}
{% endblock content %}

mmorpg_bbs/bbs/templates/bbs/search.html
{% extends 'bbs/base.html' %}


{% block nav_search_class %}active{% endblock %}

{% block title %}
Search
{% endblock title %}

{% load crispy_forms_tags %}

{% block content %}
    <h2>Found: {{ filter.qs|length }}</h2>
    <hr>
    {% if ads %}

        <form method="GET">
            {{ filter.form|crispy }}
            <input class="btn btn-primary" type="submit" value="Найти">
        </form>

        <table class="table">
            <tr>
                <th scope="col">
                    User
                </th>
                <th scope="col">
                    Category
                </th>
                <th scope="col">
                    Title
                </th>
                <th scope="col">
                    Posted
                </th>
                <th scope="col">
                    Price
                </th>
                <th scope="col">
                    Actions
                </th>         
            </tr>
            {% for ad in filter.qs %}
            <tr>
                <td>{{ ad.user.username }}</td>
                <td>
                    {{ ad.get_category_display }}
                </td>
                <td>
                    <a href="{% url 'bbs:detail' ad.id %}">{{ ad.title }}</a>
                </td>
                <td>
                    <a href="{% url 'bbs:detail' ad.id %}">{{ ad.created|date:'d M Y H:s' }}</a>
                </td>
                <td>{{ ad.price }}</td>
                <td>
                    <a class="btn btn-sm btn-outline-primary m-1" href="{% url 'bbs:detail' ad.id %}" role="button">
                        <i class="bi bi-binoculars"></i>
                        View
                    </a>
                    {% if user == ad.user %}
                        <a class="btn btn-sm btn-outline-warning m-1" href="{% url 'bbs:edit' ad.id %}" role="button">
                            <i class="bi bi-pencil"></i>
                            Edit
                        </a>
                        <a class="btn btn-sm btn-outline-danger m-1" href="{% url 'bbs:delete' ad.id %}" role="button">
                            <i class="bi bi-trash"></i>
                            Delete
                        </a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6" align="center">Nothing found!</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Nothing to show =(</h2>
    {% endif %}
{% endblock content %}